service: cleanup-deploys

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: eu-west-2
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}


# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetBucketLocation"
        - "s3:ListAllMyBuckets"
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:DeleteObject"
        - "s3:DeleteBucket"
      Resource: "arn:aws:s3:::*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"


functions:
  cleanup:
    handler: cleanupDeploys/handler.cleanup

    events:
        - schedule: rate(5 minutes)

resources:
  Resources:
    BucketsDBTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "bucket_name"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "bucket_name"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
